<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br" xml:lang="pt-br"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Apêndice B - Materiais, Métodos e Resultados da Etapa 1: Observatório do Mercado Imobiliário – Relatório 1T2026</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./93-metodo-etapa02.html" rel="next">
<link href="./91-fluxo.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-27c261d06b905028a18691de25d09dde.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
<link rel="stylesheet" href="cover-style.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./91-fluxo.html">Apêndices</a></li><li class="breadcrumb-item"><a href="./92-metodo-etapa01.html"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Materiais, Métodos e Resultados da Etapa 1: Observatório do Mercado Imobiliário</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Relatório 1T2026</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/LabFSG-UFSC/Rel_1T2026/" title="Código fonte" class="quarto-navigation-tool px-1" aria-label="Código fonte"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Baixar" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Baixar"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Relatório-1T2026.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Baixar PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Relatório-1T2026.epub">
              <i class="bi bi-journal pe-1"></i>
            Baixar ePub
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Compartilhar" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Compartilhar"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apresentação</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introdução</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-sintese.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Síntese do Avanço no Período</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-status.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Status Geral do Projeto por Etapa</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-resultados.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Principais Resultados Estratégicos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-desafios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Desafios e riscos estruturais</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ppassos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Proximos passos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-entregas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Principais Entregas do Trimestre</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-conclusao.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Considerações Finais</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Apêndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar seção">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./91-fluxo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Fluxo Metodológico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./92-metodo-etapa01.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Materiais, Métodos e Resultados da Etapa 1: Observatório do Mercado Imobiliário</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./93-metodo-etapa02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Materiais, Métodos e Resultados da Etapa 2 - Bases Cartográficas Territoriais</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./94-metodo-etapa03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Materiais, Métodos e Resultados da Etapa 3 - Modelagem e Planta de Valores Genéricos (PVG)</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução"><span class="header-section-number">B.1</span> Introdução</a></li>
  <li><a href="#fluxo-de-dados-estruturado" id="toc-fluxo-de-dados-estruturado" class="nav-link" data-scroll-target="#fluxo-de-dados-estruturado"><span class="header-section-number">B.2</span> Fluxo de dados estruturado</a>
  <ul>
  <li><a href="#fontes-de-dados" id="toc-fontes-de-dados" class="nav-link" data-scroll-target="#fontes-de-dados"><span class="header-section-number">B.2.1</span> Fontes de dados</a>
  <ul class="collapse">
  <li><a href="#dados-de-ofertas-imobiliárias-mercado" id="toc-dados-de-ofertas-imobiliárias-mercado" class="nav-link" data-scroll-target="#dados-de-ofertas-imobiliárias-mercado"><span class="header-section-number">B.2.1.1</span> Dados de Ofertas Imobiliárias (Mercado)</a></li>
  <li><a href="#dados-de-referência-espacial-oficial-governo" id="toc-dados-de-referência-espacial-oficial-governo" class="nav-link" data-scroll-target="#dados-de-referência-espacial-oficial-governo"><span class="header-section-number">B.2.1.2</span> Dados de Referência Espacial Oficial (Governo)</a></li>
  </ul></li>
  <li><a href="#ingestão" id="toc-ingestão" class="nav-link" data-scroll-target="#ingestão"><span class="header-section-number">B.2.2</span> Ingestão</a>
  <ul class="collapse">
  <li><a href="#extração-e-carga-inicial" id="toc-extração-e-carga-inicial" class="nav-link" data-scroll-target="#extração-e-carga-inicial"><span class="header-section-number">B.2.2.1</span> Extração e Carga Inicial</a></li>
  <li><a href="#setup-de-infraestrutura-e-banco-de-dados" id="toc-setup-de-infraestrutura-e-banco-de-dados" class="nav-link" data-scroll-target="#setup-de-infraestrutura-e-banco-de-dados"><span class="header-section-number">B.2.2.2</span> Setup de Infraestrutura e Banco de Dados</a></li>
  <li><a href="#otimização-de-índices-gin" id="toc-otimização-de-índices-gin" class="nav-link" data-scroll-target="#otimização-de-índices-gin"><span class="header-section-number">B.2.2.3</span> Otimização de Índices (GIN)</a></li>
  <li><a href="#fluxo-de-processamento-alto-nível" id="toc-fluxo-de-processamento-alto-nível" class="nav-link" data-scroll-target="#fluxo-de-processamento-alto-nível"><span class="header-section-number">B.2.2.4</span> Fluxo de Processamento (Alto Nível)</a></li>
  </ul></li>
  <li><a href="#tratamento" id="toc-tratamento" class="nav-link" data-scroll-target="#tratamento"><span class="header-section-number">B.2.3</span> Tratamento</a>
  <ul class="collapse">
  <li><a href="#normalização-e-geocodificação-primária-pyspark-etl" id="toc-normalização-e-geocodificação-primária-pyspark-etl" class="nav-link" data-scroll-target="#normalização-e-geocodificação-primária-pyspark-etl"><span class="header-section-number">B.2.3.1</span> Normalização e Geocodificação Primária (PySpark ETL)</a></li>
  <li><a href="#saneamento-de-registros-detecção-de-outliers" id="toc-saneamento-de-registros-detecção-de-outliers" class="nav-link" data-scroll-target="#saneamento-de-registros-detecção-de-outliers"><span class="header-section-number">B.2.3.2</span> Saneamento de Registros (Detecção de Outliers)</a></li>
  <li><a href="#validação-cruzada-avançada-geocoder-v3---postgis" id="toc-validação-cruzada-avançada-geocoder-v3---postgis" class="nav-link" data-scroll-target="#validação-cruzada-avançada-geocoder-v3---postgis"><span class="header-section-number">B.2.3.3</span> Validação Cruzada Avançada (Geocoder V3 - PostGIS)</a></li>
  <li><a href="#veredito-e-tolerância-dinâmica" id="toc-veredito-e-tolerância-dinâmica" class="nav-link" data-scroll-target="#veredito-e-tolerância-dinâmica"><span class="header-section-number">B.2.3.4</span> Veredito e Tolerância Dinâmica</a></li>
  <li><a href="#triagem-de-precisão-e-recuperação-espacial-vias-curtas" id="toc-triagem-de-precisão-e-recuperação-espacial-vias-curtas" class="nav-link" data-scroll-target="#triagem-de-precisão-e-recuperação-espacial-vias-curtas"><span class="header-section-number">B.2.3.5</span> Triagem de Precisão e Recuperação Espacial (Vias Curtas)</a></li>
  </ul></li>
  <li><a href="#armazenamento" id="toc-armazenamento" class="nav-link" data-scroll-target="#armazenamento"><span class="header-section-number">B.2.4</span> Armazenamento</a></li>
  </ul></li>
  <li><a href="#resultados-obtidos-v3" id="toc-resultados-obtidos-v3" class="nav-link" data-scroll-target="#resultados-obtidos-v3"><span class="header-section-number">B.3</span> Resultados Obtidos (V3)</a>
  <ul>
  <li><a href="#estrutura" id="toc-estrutura" class="nav-link" data-scroll-target="#estrutura"><span class="header-section-number">B.3.1</span> Estrutura</a></li>
  <li><a href="#bases-consolidadas-v3" id="toc-bases-consolidadas-v3" class="nav-link" data-scroll-target="#bases-consolidadas-v3"><span class="header-section-number">B.3.2</span> Bases Consolidadas (V3)</a>
  <ul class="collapse">
  <li><a href="#decisão-sobre-coordenadas-finais" id="toc-decisão-sobre-coordenadas-finais" class="nav-link" data-scroll-target="#decisão-sobre-coordenadas-finais"><span class="header-section-number">B.3.2.1</span> Decisão sobre Coordenadas Finais</a></li>
  <li><a href="#análise-de-conformidade-150m" id="toc-análise-de-conformidade-150m" class="nav-link" data-scroll-target="#análise-de-conformidade-150m"><span class="header-section-number">B.3.2.2</span> Análise de Conformidade (≤150m)</a></li>
  <li><a href="#estatísticas-de-distância-registros-com-match" id="toc-estatísticas-de-distância-registros-com-match" class="nav-link" data-scroll-target="#estatísticas-de-distância-registros-com-match"><span class="header-section-number">B.3.2.3</span> Estatísticas de Distância (registros com match)</a></li>
  <li><a href="#performance-por-tipo-de-imóvel" id="toc-performance-por-tipo-de-imóvel" class="nav-link" data-scroll-target="#performance-por-tipo-de-imóvel"><span class="header-section-number">B.3.2.4</span> Performance por Tipo de Imóvel</a></li>
  <li><a href="#distribuição-por-nível-de-matching-cnefe" id="toc-distribuição-por-nível-de-matching-cnefe" class="nav-link" data-scroll-target="#distribuição-por-nível-de-matching-cnefe"><span class="header-section-number">B.3.2.5</span> Distribuição por Nível de Matching CNEFE</a></li>
  </ul></li>
  <li><a href="#dicionário-de-dados-v3" id="toc-dicionário-de-dados-v3" class="nav-link" data-scroll-target="#dicionário-de-dados-v3"><span class="header-section-number">B.3.3</span> Dicionário de dados (V3)</a></li>
  </ul></li>
  <li><a href="#sec-analises-aprofundadas" id="toc-sec-analises-aprofundadas" class="nav-link" data-scroll-target="#sec-analises-aprofundadas"><span class="header-section-number">B.4</span> Análises Aprofundadas e Validação</a>
  <ul>
  <li><a href="#metodologia-de-recuperação-vias-curtas-short-streets" id="toc-metodologia-de-recuperação-vias-curtas-short-streets" class="nav-link" data-scroll-target="#metodologia-de-recuperação-vias-curtas-short-streets"><span class="header-section-number">B.4.1</span> 1. Metodologia de Recuperação: Vias Curtas (Short Streets)</a>
  <ul class="collapse">
  <li><a href="#metodologia" id="toc-metodologia" class="nav-link" data-scroll-target="#metodologia"><span class="header-section-number">B.4.1.1</span> Metodologia</a></li>
  <li><a href="#resultados" id="toc-resultados" class="nav-link" data-scroll-target="#resultados"><span class="header-section-number">B.4.1.2</span> Resultados</a></li>
  </ul></li>
  <li><a href="#sec-lote-terreno" id="toc-sec-lote-terreno" class="nav-link" data-scroll-target="#sec-lote-terreno"><span class="header-section-number">B.4.2</span> Análise Exploratória: Desempenho em Lotes e Terrenos</a>
  <ul class="collapse">
  <li><a href="#metodologia-1" id="toc-metodologia-1" class="nav-link" data-scroll-target="#metodologia-1"><span class="header-section-number">B.4.2.1</span> Metodologia</a></li>
  <li><a href="#resultados-1" id="toc-resultados-1" class="nav-link" data-scroll-target="#resultados-1"><span class="header-section-number">B.4.2.2</span> Resultados</a></li>
  </ul></li>
  <li><a href="#validação-de-acurácia-benchmarking-com-google-maps" id="toc-validação-de-acurácia-benchmarking-com-google-maps" class="nav-link" data-scroll-target="#validação-de-acurácia-benchmarking-com-google-maps"><span class="header-section-number">B.4.3</span> Validação de Acurácia (Benchmarking com Google Maps)</a>
  <ul class="collapse">
  <li><a href="#metodologia-2" id="toc-metodologia-2" class="nav-link" data-scroll-target="#metodologia-2"><span class="header-section-number">B.4.3.1</span> Metodologia</a></li>
  <li><a href="#resultados-sintéticos" id="toc-resultados-sintéticos" class="nav-link" data-scroll-target="#resultados-sintéticos"><span class="header-section-number">B.4.3.2</span> Resultados Sintéticos</a></li>
  <li><a href="#principais-conclusões-do-estudo" id="toc-principais-conclusões-do-estudo" class="nav-link" data-scroll-target="#principais-conclusões-do-estudo"><span class="header-section-number">B.4.3.3</span> Principais Conclusões do Estudo</a></li>
  </ul></li>
  <li><a href="#recomendações-e-próximos-passos" id="toc-recomendações-e-próximos-passos" class="nav-link" data-scroll-target="#recomendações-e-próximos-passos"><span class="header-section-number">B.4.4</span> Recomendações e Próximos Passos</a></li>
  </ul></li>
  <li><a href="#desafios" id="toc-desafios" class="nav-link" data-scroll-target="#desafios"><span class="header-section-number">B.5</span> Desafios</a>
  <ul>
  <li><a href="#qualidade-de-dados" id="toc-qualidade-de-dados" class="nav-link" data-scroll-target="#qualidade-de-dados"><span class="header-section-number">B.5.1</span> Qualidade de dados</a></li>
  <li><a href="#validação-posicional-e-integridade-da-oferta-são-processos-independentes" id="toc-validação-posicional-e-integridade-da-oferta-são-processos-independentes" class="nav-link" data-scroll-target="#validação-posicional-e-integridade-da-oferta-são-processos-independentes"><span class="header-section-number">B.5.2</span> Validação Posicional e Integridade da Oferta são Processos Independentes</a>
  <ul class="collapse">
  <li><a href="#problema-crítico-lotesterrenos" id="toc-problema-crítico-lotesterrenos" class="nav-link" data-scroll-target="#problema-crítico-lotesterrenos"><span class="header-section-number">B.5.2.1</span> Problema Crítico: Lotes/Terrenos</a></li>
  </ul></li>
  <li><a href="#padronização" id="toc-padronização" class="nav-link" data-scroll-target="#padronização"><span class="header-section-number">B.5.3</span> Padronização</a></li>
  <li><a href="#integração" id="toc-integração" class="nav-link" data-scroll-target="#integração"><span class="header-section-number">B.5.4</span> Integração</a></li>
  </ul></li>
  <li><a href="#escalabilidade" id="toc-escalabilidade" class="nav-link" data-scroll-target="#escalabilidade"><span class="header-section-number">B.6</span> Escalabilidade</a>
  <ul>
  <li><a href="#replicabilidade-do-modelo" id="toc-replicabilidade-do-modelo" class="nav-link" data-scroll-target="#replicabilidade-do-modelo"><span class="header-section-number">B.6.1</span> Replicabilidade do modelo</a></li>
  <li><a href="#dependências-externas" id="toc-dependências-externas" class="nav-link" data-scroll-target="#dependências-externas"><span class="header-section-number">B.6.2</span> Dependências externas</a></li>
  </ul></li>
  <li><a href="#conclusão" id="toc-conclusão" class="nav-link" data-scroll-target="#conclusão"><span class="header-section-number">B.7</span> Conclusão</a>
  <ul>
  <li><a href="#resultado-final-base-duplamente-validada" id="toc-resultado-final-base-duplamente-validada" class="nav-link" data-scroll-target="#resultado-final-base-duplamente-validada"><span class="header-section-number">B.7.1</span> Resultado Final: Base Duplamente Validada</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/LabFSG-UFSC/Rel_1T2026/edit/main/92-metodo-etapa01.qmd" class="toc-action"><i class="bi bi-github"></i>Editar essa página</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./91-fluxo.html">Apêndices</a></li><li class="breadcrumb-item"><a href="./92-metodo-etapa01.html"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Materiais, Métodos e Resultados da Etapa 1: Observatório do Mercado Imobiliário</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-obs" class="quarto-section-identifier">Apêndice B - Materiais, Métodos e Resultados da Etapa 1: Observatório do Mercado Imobiliário</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introdução" class="level2" data-number="B.1">
<h2 data-number="B.1" class="anchored" data-anchor-id="introdução"><span class="header-section-number">B.1</span> Introdução</h2>
<p>O presente relatório detalha a metodologia e os resultados da Prova de Conceito (POC) do Observatório do Mercado Imobiliário (OMI), realizada em Florianópolis/SC. O monitoramento do mercado por meio de dados de portais web é uma prática consolidada na América Latina como instrumento de apoio à avaliação em massa e à política fiscal. Neste contexto, o objetivo principal deste projeto é construir uma base de dados limpa e confiável para apoiar a Receita Federal do Brasil (RFB) no cálculo do Valor de Referência do Cadastro Imobiliário Brasileiro (CIB), superando a dependência de informações puramente autodeclaradas.</p>
<p>O desafio prático não é novo: embora a coleta massiva de dados brutos de mercado já seja uma rotina tecnológica difundida; garantir que cada evento tenha localização confiável e atributos íntegros o suficiente para uma análise fiscal rigorosa é o verdadeiro obstáculo. Os dados brutos extraídos de portais comerciais chegam com dois tipos críticos de ruído:</p>
<ul>
<li><p>Ruído Posicional: CEPs incorretos, números de porta ausentes e coordenadas deslocadas em centenas de metros — imprecisões suficientes para vincular um imóvel ao setor censitário errado.</p></li>
<li><p>Ruído Cadastral: duplicatas do mesmo imóvel em anúncios distintos, valores de área ou preço estatisticamente anômalos, campos obrigatórios ausentes e terminologias fora do padrão da administração pública.</p></li>
</ul>
<p>Esta POC estruturou um pipeline que ataca os dois problemas em paralelo e de forma independente. Para sanar a questão posicional, adotamos o Cadastro Nacional de Endereços para Fins Estatísticos (CNEFE), do IBGE, como nossa referência oficial (ground truth), aliado ao desenvolvimento de um motor de processamento próprio, o Geocoder V3. Esse motor aplica uma lógica de matching em cascata para cruzar, corrigir e qualificar cada registro contra a malha viária oficial. Simultaneamente, o sistema executa um saneamento cadastral robusto para identificar redundâncias e anomalias econômicas.</p>
<p>O resultado é que cada oferta recebe dois flags independentes, integridade cadastral e validação posicional, que podem ser combinados conforme o objetivo da análise. A POC processou 83.869 ofertas brutas de novembro de 2025 em Florianópolis.</p>
</section>
<section id="fluxo-de-dados-estruturado" class="level2" data-number="B.2">
<h2 data-number="B.2" class="anchored" data-anchor-id="fluxo-de-dados-estruturado"><span class="header-section-number">B.2</span> Fluxo de dados estruturado</h2>
<p>O Fluxo detalhado desta etapa encontra-se no apêndice 1</p>
<section id="fontes-de-dados" class="level3" data-number="B.2.1">
<h3 data-number="B.2.1" class="anchored" data-anchor-id="fontes-de-dados"><span class="header-section-number">B.2.1</span> Fontes de dados</h3>
<p>Para a realização desta Prova de Conceito (POC) em Florianópolis, o Observatório do Mercado Imobiliário estruturou seu fluxo analítico apoiando-se em duas fontes primárias de dados. Embora distintas em sua natureza e propósito original, essas fontes atuam de forma complementar para alcançar o objetivo central: validar e enriquecer espacialmente a amostra imobiliária, garantindo o rigor exigido pela Receita Federal do Brasil (RFB).</p>
<section id="dados-de-ofertas-imobiliárias-mercado" class="level4" data-number="B.2.1.1">
<h4 data-number="B.2.1.1" class="anchored" data-anchor-id="dados-de-ofertas-imobiliárias-mercado"><span class="header-section-number">B.2.1.1</span> Dados de Ofertas Imobiliárias (Mercado)</h4>
<p>A base que confere o contexto transacional e as características intrínsecas dos imóveis é oriunda de anúncios coletados em portais de mercado, especificamente do <strong>Viva Real</strong>. Esta fonte reflete a dinâmica contemporânea de ofertas (tanto para venda quanto para aluguel) e concentra os atributos cruciais para a modelagem estatística e de precificação.</p>
<ul>
<li><p><strong>Formato e Armazenamento:</strong> os dados brutos foram previamente extraídos e estão armazenados de forma particionada e otimizada no Datalake do projeto, padronizados no formato estruturado <strong>Parquet</strong>.</p></li>
<li><p><strong>Volume da POC:</strong> a amostra isolada para o município de Florianópolis (SC), com data de referência em novembro de 2025, totalizou <strong>83.869 registros brutos</strong>.</p></li>
<li><p><strong>Atributos Transacionais e Estruturais:</strong> a base compreende uma extensa gama de variáveis estruturais e textuais do imóvel (tais como tipologia, área total e útil, número de quartos, suítes, vagas de garagem, valor do imóvel, IPTU, taxa condominial, além de descrições em texto livre e amenidades).</p></li>
<li><p><strong>Atributos Locacionais e Geocodificação Primária:</strong> os anunciantes fornecem dados básicos de localização (CEP, logradouro, número, bairro). Originalmente, este conjunto de dados já contava com uma camada de geolocalização primária processada pela <strong>API do ArcGIS</strong>, que atribuiu coordenadas iniciais (latitude/longitude) e um indicador de confiança interno denominado <code>precisao</code>. Para garantir a eficácia metodológica da nossa validação cruzada, o escopo da POC foi afunilado para os <strong>61.416 registros</strong> (aproximadamente 73,2% do total) que apresentavam o indicador <code>precisao = 4</code> — nível máximo de exatidão do ArcGIS, que indica teoreticamente a localização exata ao nível do número da porta.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/omi/obs.png" class="img-fluid figure-img" alt="Mapa da distribução dos dados no Município de Florianópolis"></p>
<figcaption>Mapa de Ofertas</figcaption>
</figure>
</div></li>
</ul>
</section>
<section id="dados-de-referência-espacial-oficial-governo" class="level4" data-number="B.2.1.2">
<h4 data-number="B.2.1.2" class="anchored" data-anchor-id="dados-de-referência-espacial-oficial-governo"><span class="header-section-number">B.2.1.2</span> Dados de Referência Espacial Oficial (Governo)</h4>
<p>Para atuar como contraponto metodológico e validador irrefutável da geocodificação primária do mercado (ArcGIS), o projeto integrou o <strong>CNEFE (Cadastro Nacional de Endereços para Fins Estatísticos)</strong>.</p>
<ul>
<li><strong>Origem e Confiabilidade:</strong> Tratando-se da base oficial de endereços do território nacional, o CNEFE é gerido, auditado e periodicamente atualizado pelo <strong>Instituto Brasileiro de Geografia e Estatística (IBGE)</strong>. Por conter coordenadas atestadas por profissionais de cartografia governamental, o cadastro cobre virtualmente a totalidade dos endereços válidos e estruturados no Brasil.</li>
<li><strong>Relevância Estratégica e Fonte da Verdade:</strong> A adoção do CNEFE transcende a mera consulta; ele é o pilar que alinha o Observatório às rigorosas premissas de conformidade exigidas pela RFB. Neste projeto, o CNEFE assume o papel metodológico de <strong>“fonte da verdade”</strong> posicional, balizando qualquer divergência de localização.</li>
<li><strong>Atributos-Chave e Precisão Dinâmica:</strong> Cada endereço oficial do CNEFE aporta uma chave de identificação única e inalterável (<code>cod_unico_endereco</code>), além de padronizar componentes textuais (logradouro, bairro e o CEP com sua grafia correta). O grande diferencial técnico para o sucesso desta etapa foi a extração do atributo <code>nv_geo_coord</code> (nível de precisão geográfica do IBGE). Esta métrica, que varia numa escala de 1 (precisão exata, validada no nível da edificação) a 6 (estimativa espacial ampla, no nível de setor censitário), foi o motor que permitiu ao nosso modelo definir dinamicamente os <em>thresholds</em> (limites de tolerância em metros) para aceitar, penalizar ou descartar sumariamente as coordenadas sugeridas pelo mercado.</li>
</ul>
</section>
</section>
<section id="ingestão" class="level3" data-number="B.2.2">
<h3 data-number="B.2.2" class="anchored" data-anchor-id="ingestão"><span class="header-section-number">B.2.2</span> Ingestão</h3>
<p>A etapa de ingestão foi desenhada para conectar eficientemente o acervo do Datalake aos motores de geoprocessamento em banco de dados, assegurando que o grande volume de dados (milhares de coordenadas e endereços textuais) fosse transferido, normalizado e indexado de forma idempotente e performática.</p>
<section id="extração-e-carga-inicial" class="level4" data-number="B.2.2.1">
<h4 data-number="B.2.2.1" class="anchored" data-anchor-id="extração-e-carga-inicial"><span class="header-section-number">B.2.2.1</span> Extração e Carga Inicial</h4>
<p>Os dados brutos do portal imobiliário (Viva Real) foram lidos diretamente do Datalake, onde repousam em formato Parquet. O processo de extração não se limitou a carregar as variáveis locacionais (CEP, Bairro, Rua, Número, Latitude e Longitude geradas pelo ArcGIS), mas também trouxe consigo os atributos transacionais (área, valor, tipologia) que são o insumo principal para a modelagem estatística futura.</p>
</section>
<section id="setup-de-infraestrutura-e-banco-de-dados" class="level4" data-number="B.2.2.2">
<h4 data-number="B.2.2.2" class="anchored" data-anchor-id="setup-de-infraestrutura-e-banco-de-dados"><span class="header-section-number">B.2.2.2</span> Setup de Infraestrutura e Banco de Dados</h4>
<p>A ingestão foi roteada para um banco de dados relacional robusto — <strong>PostgreSQL (RDS hospedado na AWS)</strong>. Para viabilizar as comparações espaciais e textuais avançadas, a etapa de <em>setup</em> inicial do script garantiu a ativação de três extensões fundamentais no PostgreSQL:</p>
<ul>
<li><strong><code>postgis</code></strong>: Habilita tipos de dados espaciais (<code>GEOMETRY</code>) e funções matemáticas complexas (como <code>ST_Distance</code>) para cálculo preciso da divergência em metros entre as coordenadas.</li>
<li><strong><code>pg_trgm</code></strong>: Permite a quebra de textos em sequências de três caracteres (trigramas), essencial para buscas de similaridade (Fuzzy) em endereços com erros de digitação.</li>
<li><strong><code>unaccent</code></strong>: Garante a normalização de strings removendo acentos diacríticos (ex: igualando “São João” a “Sao Joao”).</li>
</ul>
</section>
<section id="otimização-de-índices-gin" class="level4" data-number="B.2.2.3">
<h4 data-number="B.2.2.3" class="anchored" data-anchor-id="otimização-de-índices-gin"><span class="header-section-number">B.2.2.3</span> Otimização de Índices (GIN)</h4>
<p>Para que as comparações não resultassem em gargalos de performance (“<em>full table scans</em>”), a etapa de ingestão arquitetou a criação concorrente (<code>CONCURRENTLY</code>) de índices altamente otimizados. Destaca-se o uso do <strong>GIN Index (Generalized Inverted Index)</strong> sobre as colunas de logradouros do CNEFE, utilizando as operações trigramáticas (<code>gin_trgm_ops</code>). Isso permitiu que o banco resolvesse consultas complexas de similaridade textual de maneira imediata.</p>
</section>
<section id="fluxo-de-processamento-alto-nível" class="level4" data-number="B.2.2.4">
<h4 data-number="B.2.2.4" class="anchored" data-anchor-id="fluxo-de-processamento-alto-nível"><span class="header-section-number">B.2.2.4</span> Fluxo de Processamento (Alto Nível)</h4>
<p>Todo o pipeline de ingestão e preparação culmina no roteamento estruturado para o motor de validação. O fluxo de alto nível se dá na seguinte arquitetura:</p>
<ol type="1">
<li><strong>Entrada:</strong> Filtro dos 54.007 registros alvo (onde <code>precisao = 4</code>).</li>
<li><strong>Setup Idempotente:</strong> Criação/Validação de extensões, índices e da tabela de destino <code>_projeto_rf.monit_2025_11_poc_floripa_v3</code>.</li>
<li><strong>Cascata de Processamento:</strong> Os dados recém-ingestados são despachados para os múltiplos níveis de validação (L1 a L6) do Geocoder V3.</li>
<li><strong>Enriquecimento:</strong> Emissão de resultados espaciais paralelos, calculando dinamicamente a diferença em metros e as regras de aceite.</li>
</ol>
</section>
</section>
<section id="tratamento" class="level3" data-number="B.2.3">
<h3 data-number="B.2.3" class="anchored" data-anchor-id="tratamento"><span class="header-section-number">B.2.3</span> Tratamento</h3>
<p>O processo de tratamento dos dados é a espinha dorsal metodológica do Observatório, dividido em duas macro-etapas: a padronização e geocodificação no Datalake (fase preparatória) e o <em>matching</em> cruzado em banco de dados (fase de validação).</p>
<section id="normalização-e-geocodificação-primária-pyspark-etl" class="level4" data-number="B.2.3.1">
<h4 data-number="B.2.3.1" class="anchored" data-anchor-id="normalização-e-geocodificação-primária-pyspark-etl"><span class="header-section-number">B.2.3.1</span> Normalização e Geocodificação Primária (PySpark ETL)</h4>
<p>Antes de chegar ao banco relacional, os dados brutos oriundos das diversas safras mensais do Viva Real são harmonizados no Datalake utilizando <strong>Apache Spark (PySpark)</strong>.</p>
<section id="de-para-semântico" class="level5" data-number="B.2.3.1.1">
<h5 data-number="B.2.3.1.1" class="anchored" data-anchor-id="de-para-semântico"><span class="header-section-number">B.2.3.1.1</span> De-Para Semântico</h5>
<p>Os dados brutos coletados frequentemente apresentam termos em inglês ou formatos não padronizados. Durante a etapa de ETL no PySpark, essas propriedades foram rigorosamente higienizadas, tipadas e padronizadas para o vernáculo da Receita Federal. O mapeamento inclui a tradução de tipos de anúncio e tipologias de imóvel, bem como o enquadramento estrutural das colunas no formato canônico da tabela destino, seguindo estritamente as diretrizes do Dicionário de Dados do projeto.</p>
</section>
<section id="higienização-e-geocodificação" class="level5" data-number="B.2.3.1.2">
<h5 data-number="B.2.3.1.2" class="anchored" data-anchor-id="higienização-e-geocodificação"><span class="header-section-number">B.2.3.1.2</span> Higienização e Geocodificação</h5>
<ul>
<li><strong>Higienização de Strings:</strong> Os atributos de endereço passam por funções escalares (UDFs) que removem caracteres especiais, acentos (normalização NFKD) e padronizam a caixa alta, gerando chaves limpas para cruzamento.</li>
<li><strong>Cálculo da Precisão Inicial:</strong> O script Spark roda uma lógica hierárquica para determinar o grau de confiança da informação inserida pelo corretor (a coluna <code>precisao</code>). Um endereço só recebe <code>precisao = 4</code> se contiver Rua, Número, Bairro e Cidade devidamente preenchidos.</li>
<li><strong>Geocodificação via ArcGIS:</strong> Para os registros novos que ainda não possuem coordenadas em nossa base histórica (<code>tb_localizacao</code>), o pipeline do Spark efetua chamadas assíncronas (com estratégias de <em>retry</em> exponencial) à API do ArcGIS para obter a primeira coordenada (<code>lat</code> e <code>lon</code>). Esta coordenada “crua” do mercado é o que será auditado a seguir.</li>
</ul>
<p>O código-fonte completo do pipeline está disponível em <a href="scripts.qmd#sec-script-etl">Apêndice — ETL PySpark</a>.</p>
</section>
</section>
<section id="saneamento-de-registros-detecção-de-outliers" class="level4" data-number="B.2.3.2">
<h4 data-number="B.2.3.2" class="anchored" data-anchor-id="saneamento-de-registros-detecção-de-outliers"><span class="header-section-number">B.2.3.2</span> Saneamento de Registros (Detecção de Outliers)</h4>
<p>Antes de qualquer validação geoespacial, o pipeline executa um <strong>sistema robusto de detecção de outliers</strong> que identifica e classifica dados problemáticos nos anúncios imobiliários.</p>
<section id="objetivo-da-etapa" class="level5" data-number="B.2.3.2.1">
<h5 data-number="B.2.3.2.1" class="anchored" data-anchor-id="objetivo-da-etapa"><span class="header-section-number">B.2.3.2.1</span> Objetivo da Etapa</h5>
<p>Garantir que: - Análises estatísticas não sejam distorcidas por dados duplicados ou absurdos - Problemas óbvios (quartos impossíveis, preços extremos) sejam sinalizados - Cada registro seja classificado segundo nível de confiança - Bolsistas possam priorizar manually os casos mais críticos</p>
</section>
<section id="códigos-de-classificação" class="level5" data-number="B.2.3.2.2">
<h5 data-number="B.2.3.2.2" class="anchored" data-anchor-id="códigos-de-classificação"><span class="header-section-number">B.2.3.2.2</span> Códigos de Classificação</h5>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Código</th>
<th>Status</th>
<th>Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>0</strong></td>
<td>Válido</td>
<td>Registro aprovado para análises</td>
</tr>
<tr class="even">
<td><strong>1</strong></td>
<td>Duplicado</td>
<td>Mesmo imóvel anunciado múltiplas vezes</td>
</tr>
<tr class="odd">
<td><strong>2</strong></td>
<td>Com Outliers</td>
<td>Possui um ou mais problemas detectados</td>
</tr>
<tr class="even">
<td><strong>3</strong></td>
<td>Inválido</td>
<td>Campos essenciais ausentes/impossíveis</td>
</tr>
</tbody>
</table>
</section>
<section id="tipos-de-problemas-detectados" class="level5" data-number="B.2.3.2.3">
<h5 data-number="B.2.3.2.3" class="anchored" data-anchor-id="tipos-de-problemas-detectados"><span class="header-section-number">B.2.3.2.3</span> Tipos de Problemas Detectados</h5>
<p>O sistema identifica <strong>10 categorias</strong> de anomalias:</p>
<ul>
<li><code>duplicado</code> — Mesmo imóvel em múltiplos anúncios</li>
<li><code>campos_null</code> — Informações essenciais faltando</li>
<li><code>quartos</code> — Quantidade impossível ou inconsistente</li>
<li><code>suites</code> — Mais suítes que quartos</li>
<li><code>banheiros</code> — Quantidade impossível</li>
<li><code>vagas</code> — Garagem inconsistente</li>
<li><code>valor</code> — Preço extremamente alto ou baixo</li>
<li><code>area</code> — Tamanho impossível</li>
<li><code>vm2</code> — Valor/m² fisicamente impossível</li>
<li><code>vm2_estatistico</code> — Valor/m² muito fora do padrão regional (<strong>Principal Indicador</strong>)</li>
</ul>
</section>
<section id="resultados-na-poc-florianópolis" class="level5" data-number="B.2.3.2.4">
<h5 data-number="B.2.3.2.4" class="anchored" data-anchor-id="resultados-na-poc-florianópolis"><span class="header-section-number">B.2.3.2.4</span> Resultados na POC Florianópolis</h5>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Status</th>
<th>Quantidade</th>
<th>Percentual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Válidos (0)</strong></td>
<td>~65.000</td>
<td>77.5%</td>
</tr>
<tr class="even">
<td><strong>Com Outliers (2)</strong></td>
<td>~12.000</td>
<td>14.3%</td>
</tr>
<tr class="odd">
<td><strong>Duplicados (1)</strong></td>
<td>~5.200</td>
<td>6.2%</td>
</tr>
<tr class="even">
<td><strong>Inválidos (3)</strong></td>
<td>~1.669</td>
<td>2.0%</td>
</tr>
</tbody>
</table>
<p><strong>Problema mais comum:</strong> <code>vm2_estatistico</code> representa <strong>70% dos outliers</strong> detectados, confirmando que valor/m² é o melhor sinalizador de anomalias imobiliárias.</p>
</section>
<section id="implementação-técnica" class="level5" data-number="B.2.3.2.5">
<h5 data-number="B.2.3.2.5" class="anchored" data-anchor-id="implementação-técnica"><span class="header-section-number">B.2.3.2.5</span> Implementação Técnica</h5>
<p>O sistema foi implementado em <strong>PostgreSQL</strong> com o arquivo:</p>
<pre><code>relatorio_poc_floripa/script_deteccao_outliers_completo_v2.sql.sql (750+ linhas)</code></pre>
<p>O script completo está disponível em <a href="scripts.qmd#sec-script-outliers">Apêndice — Script de Detecção de Outliers</a>.</p>
<p>Adiciona as seguintes colunas na tabela: - <code>duplicado</code> — Marcação de duplicata - <code>outlier_tipos</code> — Array de tipos de problemas - <code>verificado_outliers</code> — Validação manual realizada? - <code>updated_at</code>, <code>updated_by</code>, <code>observacoes</code> — Rastreamento de correções</p>
<hr>
</section>
</section>
<section id="validação-cruzada-avançada-geocoder-v3---postgis" class="level4" data-number="B.2.3.3">
<h4 data-number="B.2.3.3" class="anchored" data-anchor-id="validação-cruzada-avançada-geocoder-v3---postgis"><span class="header-section-number">B.2.3.3</span> Validação Cruzada Avançada (Geocoder V3 - PostGIS)</h4>
<p>Com a base de mercado padronizada e as coordenadas primárias (ArcGIS) estabelecidas, o fluxo migra para a validação contra a base governamental. O <strong>Geocoder V3</strong> implementa uma cascata de seis níveis dentro do PostgreSQL: cada nível processa <strong>exclusivamente os registros que todos os níveis anteriores não resolveram</strong>. O processamento para assim que um match é encontrado — garantindo que o critério mais rigoroso sempre tenha prioridade sobre os mais permissivos. O código-fonte completo do motor está disponível em <a href="scripts.qmd#sec-script-geocoder">Apêndice — Geocoder V3</a>.</p>
<section id="pré-processamento-de-entrada" class="level5" data-number="B.2.3.3.1">
<h5 data-number="B.2.3.3.1" class="anchored" data-anchor-id="pré-processamento-de-entrada"><span class="header-section-number">B.2.3.3.1</span> Pré-processamento de Entrada</h5>
<p>Antes de entrar na cascata, cada registro é normalizado inteiramente em SQL:</p>
<ul>
<li><strong><code>cep_clean</code>:</strong> Remove o hífen do CEP (<code>88010-200</code> → <code>88010200</code>).</li>
<li><strong><code>logr_limpo</code>:</strong> Remove prefixo de tipo de logradouro (<code>Rua</code>, <code>Av.</code>, <code>Travessa</code>, <code>Servidão</code>, <code>Estrada</code> etc.) via <code>REGEXP_REPLACE</code>, aplica <code>LOWER</code> e <code>unaccent</code> — igualando grafias como <em>“Av. Beira-Mar Norte”</em> e <em>“Avenida Beira Mar Norte”</em> antes de qualquer comparação.</li>
</ul>
<p>Esta normalização é o que permite ao L1 (match “exato”) funcionar mesmo com variações menores de grafia entre portais imobiliários e o cadastro oficial.</p>
</section>
<section id="níveis-da-cascata" class="level5" data-number="B.2.3.3.2">
<h5 data-number="B.2.3.3.2" class="anchored" data-anchor-id="níveis-da-cascata"><span class="header-section-number">B.2.3.3.2</span> Níveis da Cascata</h5>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Nível</th>
<th style="text-align: left;">Nome</th>
<th style="text-align: left;">Chaves de Match</th>
<th style="text-align: center;">Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>L1</strong></td>
<td style="text-align: left;">Exact</td>
<td style="text-align: left;">CEP + Logradouro normalizado + Número exato</td>
<td style="text-align: center;">1,00 (fixo)</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>L2</strong></td>
<td style="text-align: left;">Fuzzy Number</td>
<td style="text-align: left;">CEP + Trigrama logradouro (≥ 0,40) + Número mais próximo</td>
<td style="text-align: center;">Composto</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>L3</strong></td>
<td style="text-align: left;">Interpolated</td>
<td style="text-align: left;">CEP + Logradouro exato + Interpolação entre bounds numéricos</td>
<td style="text-align: center;">Dinâmico</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>L4</strong></td>
<td style="text-align: left;">Fuzzy Street</td>
<td style="text-align: left;">CEP + Trigrama logradouro (≥ 0,40), sem número</td>
<td style="text-align: center;">Trigrama</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>L5</strong></td>
<td style="text-align: left;">Fuzzy Bairro</td>
<td style="text-align: left;">Bairro exato + Trigrama logradouro (≥ 0,40) + Número próximo</td>
<td style="text-align: center;">Composto</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>L6</strong></td>
<td style="text-align: left;">No Match</td>
<td style="text-align: left;">—</td>
<td style="text-align: center;">0,00</td>
</tr>
</tbody>
</table>
</section>
<section id="descrição-de-cada-nível" class="level5" data-number="B.2.3.3.3">
<h5 data-number="B.2.3.3.3" class="anchored" data-anchor-id="descrição-de-cada-nível"><span class="header-section-number">B.2.3.3.3</span> Descrição de Cada Nível</h5>
<p><strong>L1 — Match Exato:</strong> Correspondência de <code>cep_clean</code> + <code>logr_limpo</code> + número exato (<code>TRIM</code> em ambos os lados). Score fixo em 1,00. Respondeu por <strong>22.098 dos 54.007 matches</strong> (40,9%) — os mais confiáveis da base.</p>
<p><strong>L2 — Fuzzy Number (Score Composto):</strong> Para registros com número informado mas sem match exato, busca o número oficial mais próximo dentro do mesmo CEP. Opera com dois thresholds de trigrama distintos: um <em>pré-filtro</em> (≥ 0,35) que usa o índice GIN para eliminar candidatos sem entrar em <em>full scan</em>, e um de <em>aceitação final</em> (≥ 0,40) após o <code>LATERAL JOIN</code>. O candidato é selecionado ordenado pela menor diferença numérica e, em empate, pela melhor precisão IBGE (<code>nv_geo_coord</code>). O score pondera:</p>
<p><span class="math display">\[Score = 0{,}65 \times Simil_{trigrama} + 0{,}35 \times \frac{1}{1 + |N_{mercado} - N_{cnefe}|}\]</span></p>
<p><strong>L3 — Interpolação Linear:</strong> Quando o número não existe no CNEFE mas o CEP e logradouro existem com outros números, estima a coordenada por interpolação linear entre os dois vizinhos conhecidos (bound inferior e superior). Requer <code>logr_limpo</code> exato (sem fuzzy), garantindo que a interpolação ocorra dentro do logradouro correto. A fórmula é:</p>
<p><span class="math display">\[lat_{interp} = lat_{baixo} + \frac{N_{alvo} - N_{baixo}}{N_{alto} - N_{baixo}} \times (lat_{alto} - lat_{baixo})\]</span></p>
<p>O score parte de 0,90 e decai com o intervalo entre os bounds (<code>0,90 − 0,0001 × gap</code>). Filtro conservador: resultados com distância &gt; 500m são descartados.</p>
<p><strong>L4 — Fuzzy Street:</strong> Para registros sem número válido (ou cujo número não auxiliou nos níveis anteriores), busca apenas por similaridade de logradouro dentro do mesmo CEP — sem considerar numeração. Usa os mesmos thresholds de pré-filtro (≥ 0,35) e aceitação (≥ 0,40). É o nível com maior dispersão de distância (mediana de 252m).</p>
<p><strong>L5 — Fuzzy Bairro (sem CEP):</strong> Fallback para registros com CEP ausente ou inválido. Substitui a âncora do CEP pelo bairro exato (<code>dsc_localidade = bairro_tratado</code>) e aplica a mesma fórmula de score composto do L2. Processado em batches de 500 registros para evitar locks longos no banco. Usa índice GIN sobre <code>f_unaccent(nom_seglogr)</code> para viabilizar o pré-filtro sem CEP.</p>
<p><strong>L6 — No Match:</strong> Registros sem aderência em nenhum nível são registrados com <code>cnefe_match_type = 'no_match'</code>, <code>confidence_score = 0,00</code> e <code>is_problematic = TRUE</code>. As coordenadas do ArcGIS são mantidas como fallback, sinalizadas como <code>arcgis_nao_validado</code>.</p>
<p><strong>Nota de Evolução Metodológica (V3.3):</strong> Diferente das versões anteriores, a hierarquia do Geocoder V3.3 prioriza o matching por proximidade numérica (<strong>L2 - Fuzzy Number</strong>) em detrimento da estimativa matemática (<strong>L3 - Interpolated</strong>). Esta decisão visa mitigar erros em logradouros com numeração irregular ou CEPs únicos extensos — cenários onde a interpolação linear poderia sugerir coordenadas teoricamente corretas, mas geograficamente imprecisas. Ao priorizar o match em números oficiais vizinhos já validados pelo IBGE, o modelo adota um viés conservador que aumenta a confiabilidade do dado final.</p>
</section>
</section>
<section id="veredito-e-tolerância-dinâmica" class="level4" data-number="B.2.3.4">
<h4 data-number="B.2.3.4" class="anchored" data-anchor-id="veredito-e-tolerância-dinâmica"><span class="header-section-number">B.2.3.4</span> Veredito e Tolerância Dinâmica</h4>
<p>Após encontrar o correspondente na base do CNEFE, o algoritmo utiliza o <code>ST_Distance</code> do PostGIS para calcular a diferença em metros entre a coordenada do mercado (ArcGIS) e a oficial (CNEFE). A aprovação de qual delas prevalecerá como coordenada final não é engessada, ela depende do <code>nv_geo_coord</code> (precisão original mapeada pelo IBGE):</p>
<ul>
<li><strong>Precisão IBGE 1 e 2:</strong> A coordenada do mercado só é tolerada se divergir no máximo <strong>100m</strong> da oficial (além de exigir <em>score</em> de confiança <span class="math inline">\(\geq 0{,}80\)</span>).</li>
<li><strong>Precisão IBGE 3:</strong> Tolerância de até <strong>200m</strong>.</li>
<li><strong>Precisão IBGE 4:</strong> Tolerância de até <strong>500m</strong>.</li>
<li><strong>Precisão IBGE 5 e 6:</strong> Apenas o score é avaliado (distância ignorada) — coordenada CNEFE é imprecisa demais para servir de referência métrica confiável.</li>
</ul>
<p>Quando <code>is_problematic = FALSE</code> e <code>nv_geo_coord</code> ∈ {1, 2, 3}, a coordenada <strong>CNEFE substitui</strong> a do ArcGIS como posição final do imóvel. Nos demais casos, a coordenada ArcGIS é mantida, sinalizadas como <code>arcgis_validado</code> (dentro dos limites) ou <code>arcgis_nao_validado</code> (fora dos limites).</p>
<p>Na POC de Florianópolis, esse fluxo em cascata processou cerca de <strong>52.386 registros em apenas ~2.4 minutos</strong>, representando uma melhoria de performance de 17× em relação às arquiteturas anteriores.</p>
<section id="exemplos-práticos-da-cascata" class="level5" data-number="B.2.3.4.1">
<h5 data-number="B.2.3.4.1" class="anchored" data-anchor-id="exemplos-práticos-da-cascata"><span class="header-section-number">B.2.3.4.1</span> Exemplos Práticos da Cascata</h5>
<p>Os dois exemplos abaixo ilustram como a lógica de eliminação progressiva funciona na prática.</p>
<p><strong>Exemplo 1 — Registro resolvido no L3 (trace completo da cascata)</strong></p>
<blockquote class="blockquote">
<p><strong>Entrada:</strong> Apartamento — <em>“Rua Tenente Silveira, 234, CEP 88010-300, Centro”</em></p>
<ul>
<li><strong>L1:</strong> <code>logr_limpo</code> = <code>"tenente silveira"</code> | Número 234 não consta no CNEFE para esse CEP+logradouro → <strong>reprovado</strong></li>
<li><strong>L2:</strong> Candidato mais próximo = número 200 (diff = 34). Score = 0,65 × 0,99 + 0,35 × (1 ÷ 35) = 0,643 + 0,010 = <strong>0,653</strong> → abaixo de 0,80 → <strong>reprovado</strong></li>
<li><strong>L3:</strong> Bounds encontrados: 200 (lat = −27,5901, lon = −48,5510) e 300 (lat = −27,5912, lon = −48,5523). Interpolação com <em>t</em> = (234 − 200) ÷ (300 − 200) = 0,34 → coordenada estimada. Score = 0,90 − 0,0001 × 100 = <strong>0,880</strong>. Distância ao ArcGIS = 31 m (≤ 500 m) → <strong>APROVADO ✅</strong></li>
</ul>
<p><em>Resultado: <code>cnefe_match_type = 'interpolated'</code>, <code>confidence_score = 0,880</code>, <code>is_problematic = FALSE</code>, coordenada CNEFE adotada como final.</em></p>
</blockquote>
<p><strong>Exemplo 2 — Registro sem match (L6)</strong></p>
<blockquote class="blockquote">
<p><strong>Entrada:</strong> Lote — <em>“Servidão das Flores, 80, CEP 88063-999, Lagoa da Conceição”</em></p>
<ul>
<li><strong>L1:</strong> CEP <code>88063999</code> não existe no CNEFE → <strong>reprovado</strong></li>
<li><strong>L2:</strong> CEP inválido — sem candidatos no pré-filtro → <strong>reprovado</strong></li>
<li><strong>L3:</strong> Sem bounds possíveis pelo CEP inválido → <strong>reprovado</strong></li>
<li><strong>L4:</strong> CEP inválido — sem candidatos pelo CEP → <strong>reprovado</strong></li>
<li><strong>L5:</strong> Bairro “Lagoa da Conceição” encontrado. Trigrama de <code>"servidao das flores"</code> vs.&nbsp;candidatos CNEFE: similaridade máxima = 0,28 (&lt; 0,35 do pré-filtro) → nenhum candidato passa → <strong>reprovado</strong></li>
<li><strong>L6:</strong> Registro marcado como <code>no_match</code>, <code>confidence_score = 0,00</code>, <code>is_problematic = TRUE</code>. Coordenadas ArcGIS mantidas como fallback (<code>arcgis_nao_validado</code>).</li>
</ul>
</blockquote>
</section>
</section>
<section id="triagem-de-precisão-e-recuperação-espacial-vias-curtas" class="level4" data-number="B.2.3.5">
<h4 data-number="B.2.3.5" class="anchored" data-anchor-id="triagem-de-precisão-e-recuperação-espacial-vias-curtas"><span class="header-section-number">B.2.3.5</span> Triagem de Precisão e Recuperação Espacial (Vias Curtas)</h4>
<p>Após a geocodificação inicial com ArcGIS, todos os registros são classificados em três categorias baseadas na coluna <code>precisao</code>:</p>
<p><strong>a) Precisão &lt; 3 (Baixa Qualidade):</strong> Registros com informações incompletas de endereço (faltam rua, número ou bairro) são descartados da análise, pois carecem de dados suficientes para validação confiável contra o CNEFE.</p>
<p><strong>b) Precisão = 4 (Alta Qualidade):</strong> Registros com todas as informações de endereço devidamente preenchidas (rua, número, bairro, CEP e cidade) prosseguem diretamente para a validação cruzada V3.</p>
<p><strong>c) Precisão = 3 (Qualidade Intermediária):</strong> Registros com informações parciais (geralmente faltando o número de porta) recebem tratamento especial através da <strong>metodologia de recuperação espacial com vias curtas</strong>.</p>
<section id="metodologia-de-recuperação-espacial-short-streets" class="level5" data-number="B.2.3.5.1">
<h5 data-number="B.2.3.5.1" class="anchored" data-anchor-id="metodologia-de-recuperação-espacial-short-streets"><span class="header-section-number">B.2.3.5.1</span> Metodologia de Recuperação Espacial (Short Streets)</h5>
<p>Para maximizar a cobertura analítica e recuperar registros de precisão 3 que possuem potencial locacional, implementou-se um procedimento operacional baseado na comparação de distâncias a vias curtas versus vias totais.</p>
<p><strong>Premissa:</strong> Uma via curta é um logradouro integralmente contido dentro de um único setor censitário. Quando um imóvel está mais próximo de uma via curta do que de qualquer outra via, infere-se que a ambiguidade territorial é menor, justificando seu reaproveitamento.</p>
<p><strong>Algoritmo resumido:</strong> Para cada registro de precisão 3, calcula-se a distância até a via curta mais próxima (máx. 100m) e até a via mais próxima da malha viária completa. Se ambas forem equivalentes (tolerância ~2–3m), o registro recebe <code>flag_reap3 = True</code> e é incorporado ao pipeline; caso contrário, é descartado.</p>
<p><strong>Bases de Dados Utilizadas:</strong></p>
<ul>
<li><code>eixos_osm_curtos.gpkg</code> — Vias curtas (contidas em 1 setor censitário)</li>
<li><code>eixos_osm_dissolvidos.gpkg</code> — Malha viária completa</li>
</ul>
<p><strong>Resultado operacional:</strong> Na POC Florianópolis, <strong>10.23% dos registros de precisão 3</strong> foram reaproveitados (1.236 de 12.077), elevando a cobertura analítica de ~73% para ~81%. A variação da taxa de reaproveitamento por bairro e tipologia, bem como a validação da metodologia, são detalhadas na <a href="#sec-analises-aprofundadas">Seção 3.1</a>.</p>
</section>
</section>
</section>
<section id="armazenamento" class="level3" data-number="B.2.4">
<h3 data-number="B.2.4" class="anchored" data-anchor-id="armazenamento"><span class="header-section-number">B.2.4</span> Armazenamento</h3>
<p>Os dados consolidados foram inseridos num banco <strong>PostgreSQL (RDS AWS)</strong> utilizando os recursos avançados das extensões PostGIS e <code>pg_trgm</code>. A tabela de saída (<code>_projeto_rf.monit_2025_11_poc_floripa_v3</code>) contém tanto as informações do anúncio original quanto as coordenadas cruzadas e o veredito do modelo.</p>
</section>
</section>
<section id="resultados-obtidos-v3" class="level2" data-number="B.3">
<h2 data-number="B.3" class="anchored" data-anchor-id="resultados-obtidos-v3"><span class="header-section-number">B.3</span> Resultados Obtidos (V3)</h2>
<section id="estrutura" class="level3" data-number="B.3.1">
<h3 data-number="B.3.1" class="anchored" data-anchor-id="estrutura"><span class="header-section-number">B.3.1</span> Estrutura</h3>
<p>Foi criada e estabilizada a estrutura completa de avaliação de distâncias e aprovação de qualidades espaciais de imóveis. O processamento abrangeu com sucesso <strong>87.9% dos imóveis elegíveis</strong> (com número informado), gerando tabelas altamente indexadas.</p>
<p><strong>Detalhamento do Funil de Qualidade:</strong></p>
<p>O pipeline foi desenhado para filtrar progressivamente o ruído do mercado, garantindo que apenas dados com alta confiabilidade posicional cheguem à análise final.</p>
<div id="tbl-funil-qualidade" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-funil-qualidade-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;B.1: Funil de processamento e validação cruzada
</figcaption>
<div aria-describedby="tbl-funil-qualidade-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Etapa do Funil</th>
<th style="text-align: left;">Registros</th>
<th style="text-align: left;">% Retenção</th>
<th style="text-align: left;">Motivo do Descarte / Observação</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Ingestão Bruta (Datalake)</strong></td>
<td style="text-align: left;">83.869</td>
<td style="text-align: left;">100%</td>
<td style="text-align: left;">Amostra total (Novembro/2025)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Filtro de Localização (Prec 3/4)</strong></td>
<td style="text-align: left;">73.493</td>
<td style="text-align: left;">87.6%</td>
<td style="text-align: left;">Endereço sem Rua ou Bairro identificado</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Elegíveis para CNEFE (V3)</strong></td>
<td style="text-align: left;">61.416</td>
<td style="text-align: left;">73.2%</td>
<td style="text-align: left;">Registros com Número de Porta (precisao=4)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Match CNEFE Identificado</strong></td>
<td style="text-align: left;">54.007</td>
<td style="text-align: left;">64.4%</td>
<td style="text-align: left;">Sucesso no cruzamento L1-L5</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Validados RFB (Final)</strong></td>
<td style="text-align: left;"><strong>25.104</strong></td>
<td style="text-align: left;"><strong>30.0%</strong></td>
<td style="text-align: left;"><strong>Alta Precisão (IBGE 1-3) e Confiança Final</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Métricas de Desempenho:</strong></p>
<ul>
<li><strong>Registros processados com match CNEFE:</strong> 54.007 (87.9% dos elegíveis)</li>
<li><strong>Registros sem match CNEFE:</strong> 7.409 (12.1% dos elegíveis)</li>
<li><strong>Tempo de processamento:</strong> ~2.4 minutos (52.386 registros/min)</li>
</ul>
</section>
<section id="bases-consolidadas-v3" class="level3" data-number="B.3.2">
<h3 data-number="B.3.2" class="anchored" data-anchor-id="bases-consolidadas-v3"><span class="header-section-number">B.3.2</span> Bases Consolidadas (V3)</h3>
<p>Como resultado primário, construímos a tabela <code>monit_2025_11_poc_floripa_v3</code>, na qual verificamos que a <strong>mediana de distância entre os provedores é de 24.35 metros</strong> e a <strong>distância média é de 215.26 metros</strong>.</p>
<section id="decisão-sobre-coordenadas-finais" class="level4" data-number="B.3.2.1">
<h4 data-number="B.3.2.1" class="anchored" data-anchor-id="decisão-sobre-coordenadas-finais"><span class="header-section-number">B.3.2.1</span> Decisão sobre Coordenadas Finais</h4>
<p>No resultado final, aplicou-se a lógica de decisão V3:</p>
<ul>
<li><strong>CNEFE escolhido como fonte definitiva:</strong> 25.104 registros (46.5%)
<ul>
<li>Critério: <code>is_problematic = FALSE</code> AND <code>nv_geo_coord</code> IN (1, 2,
<ol start="3" type="1">
<li></li>
</ol></li>
<li>Estes registros têm alta precisão IBGE (nível de edificação ou face de quadra)</li>
</ul></li>
<li><strong>ArcGIS mantido como fallback:</strong> 28.903 registros (53.5%)
<ul>
<li>Razões: CNEFE problemático (<code>is_problematic = TRUE</code>) OU precisão IBGE baixa (<code>nv_geo_coord</code> &gt;= 4)</li>
<li>Inclui casos onde distância &gt; threshold dinâmico</li>
</ul></li>
</ul>
</section>
<section id="análise-de-conformidade-150m" class="level4" data-number="B.3.2.2">
<h4 data-number="B.3.2.2" class="anchored" data-anchor-id="análise-de-conformidade-150m"><span class="header-section-number">B.3.2.2</span> Análise de Conformidade (≤150m)</h4>
<p>Dos 52.950 registros com distância calculada:</p>
<ul>
<li><strong>Dentro de 150m (Tolerável):</strong> 25.325 registros (47.83%)</li>
<li><strong>Fora de 150m (Problemático):</strong> 27.625 registros (52.17%)</li>
</ul>
<p><strong>Distribuição Detalhada por Intervalos:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Intervalo</th>
<th>Quantidade</th>
<th>Percentual</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0-10m</td>
<td>15.909</td>
<td>30.05%</td>
<td>Excelente</td>
</tr>
<tr class="even">
<td>10-50m</td>
<td>18.792</td>
<td>35.49%</td>
<td>Muito Bom</td>
</tr>
<tr class="odd">
<td>50-100m</td>
<td>5.471</td>
<td>10.33%</td>
<td>Bom</td>
</tr>
<tr class="even">
<td>100-150m</td>
<td>2.384</td>
<td>4.50%</td>
<td>Aceitável</td>
</tr>
<tr class="odd">
<td>150-300m</td>
<td>3.270</td>
<td>6.18%</td>
<td>Problemático</td>
</tr>
<tr class="even">
<td>300-500m</td>
<td>2.035</td>
<td>3.84%</td>
<td>Muito Problemático</td>
</tr>
<tr class="odd">
<td>500-1000m</td>
<td>2.792</td>
<td>5.27%</td>
<td>Crítico</td>
</tr>
<tr class="even">
<td>1000m+</td>
<td>2.297</td>
<td>4.34%</td>
<td>Crítico</td>
</tr>
</tbody>
</table>
</section>
<section id="estatísticas-de-distância-registros-com-match" class="level4" data-number="B.3.2.3">
<h4 data-number="B.3.2.3" class="anchored" data-anchor-id="estatísticas-de-distância-registros-com-match"><span class="header-section-number">B.3.2.3</span> Estatísticas de Distância (registros com match)</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Métrica</th>
<th>Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Total com distância</strong></td>
<td>52.950</td>
</tr>
<tr class="even">
<td><strong>Distância Média</strong></td>
<td>215.26 m</td>
</tr>
<tr class="odd">
<td><strong>Distância Mediana</strong></td>
<td>24.35 m</td>
</tr>
<tr class="even">
<td><strong>Distância Mínima</strong></td>
<td>0.00 m</td>
</tr>
<tr class="odd">
<td><strong>Distância Máxima</strong></td>
<td>31.357 km</td>
</tr>
</tbody>
</table>
<p>A mediana de 24.35m indica que <strong>metade dos registros tem divergência menor que 24 metros</strong>, demonstrando que o algoritmo conseguiu excelente alinhamento em grande parte dos casos. A média é inflacionada por outliers geograficamente distantes (outliers até 31 km).</p>
</section>
<section id="performance-por-tipo-de-imóvel" class="level4" data-number="B.3.2.4">
<h4 data-number="B.3.2.4" class="anchored" data-anchor-id="performance-por-tipo-de-imóvel"><span class="header-section-number">B.3.2.4</span> Performance por Tipo de Imóvel</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tipo</th>
<th>Registros</th>
<th>Processados</th>
<th>Taxa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Apartamento</strong></td>
<td>43.809</td>
<td>38.619</td>
<td>88.1%</td>
</tr>
<tr class="even">
<td><strong>Casa</strong></td>
<td>18.969</td>
<td>16.674</td>
<td>87.9%</td>
</tr>
<tr class="odd">
<td><strong>Lote/Terreno</strong></td>
<td>6.120</td>
<td>3.369</td>
<td>55.0%</td>
</tr>
<tr class="even">
<td><strong>Cobertura</strong></td>
<td>4.882</td>
<td>4.296</td>
<td>88.0%</td>
</tr>
<tr class="odd">
<td><strong>Escritório</strong></td>
<td>3.560</td>
<td>3.131</td>
<td>87.9%</td>
</tr>
<tr class="even">
<td><strong>Casa de Condomínio</strong></td>
<td>3.148</td>
<td>2.765</td>
<td>87.8%</td>
</tr>
<tr class="odd">
<td><strong>Outros</strong></td>
<td>3.228</td>
<td>2.853</td>
<td>88.4%</td>
</tr>
</tbody>
</table>
<p><strong>Achado Crítico:</strong> Lotes/Terrenos tiveram taxa de processamento significativamente inferior (55% vs 88% geral), indicando desafio específico neste segmento. As causas raiz e recomendações são detalhadas na <a href="#sec-lote-terreno">Seção 3.2</a>.</p>
</section>
<section id="distribuição-por-nível-de-matching-cnefe" class="level4" data-number="B.3.2.5">
<h4 data-number="B.3.2.5" class="anchored" data-anchor-id="distribuição-por-nível-de-matching-cnefe"><span class="header-section-number">B.3.2.5</span> Distribuição por Nível de Matching CNEFE</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Tipo de Match</th>
<th>Registros</th>
<th>Dist. Média</th>
<th>Dist. Mediana</th>
<th>Taxa de OK</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>exact_cep_street_number</strong></td>
<td>22.098</td>
<td>92.6 m</td>
<td>7.4 m</td>
<td>87.3%</td>
</tr>
<tr class="even">
<td><strong>fuzzy_number</strong></td>
<td>29.750</td>
<td>294.7 m</td>
<td>44.6 m</td>
<td>45.1%</td>
</tr>
<tr class="odd">
<td><strong>fuzzy_bairro</strong></td>
<td>564</td>
<td>300.0 m</td>
<td>64.9 m</td>
<td>32.4%</td>
</tr>
<tr class="even">
<td><strong>fuzzy_street</strong></td>
<td>527</td>
<td>783.3 m</td>
<td>252.3 m</td>
<td>18.2%</td>
</tr>
<tr class="odd">
<td><strong>interpolated</strong></td>
<td>11</td>
<td>190.4 m</td>
<td>162.0 m</td>
<td>54.5%</td>
</tr>
<tr class="even">
<td><strong>no_match</strong></td>
<td>1.057</td>
<td>—</td>
<td>—</td>
<td>0%</td>
</tr>
</tbody>
</table>
<p><strong>Interpretação:</strong> O L1 (exact) tem qualidade excepcional (87.3% dentro de 150m), mas o L2 (fuzzy_number) apresenta dispersão maior, sugerindo oportunidade de ajuste de thresholds numéricos (±50 dígitos máximo).</p>
</section>
</section>
<section id="dicionário-de-dados-v3" class="level3" data-number="B.3.3">
<h3 data-number="B.3.3" class="anchored" data-anchor-id="dicionário-de-dados-v3"><span class="header-section-number">B.3.3</span> Dicionário de dados (V3)</h3>
<p>Toda a modelagem foi devidamente mapeada no Dicionário de Dados oficial (<a href="evidencias.qmd#sec-dic-dados"><code>DICIONARIO_DADOS.md</code></a> v3). Ele detalha minuciosamente a natureza das colunas expandidas, incluindo:</p>
<ul>
<li><strong>Campos de Rastreabilidade Novos:</strong> <code>origem_coordenada</code>, <code>processo_geo</code>, <code>lat_final</code>, <code>lon_final</code>, <code>geom_final</code></li>
<li><strong>Campos de Decisão:</strong> <code>is_problematic</code> (dinâmico por <code>nv_geo_coord</code>), <code>geo_precision_score</code>, <code>cnefe_nv_geo_coord</code></li>
<li><strong>Campos Herdados:</strong> <code>confidence_score</code>, <code>distance_meters</code>, <code>cnefe_match_type</code>, <code>verificado</code></li>
</ul>
<p>Estabelece a semântica correta para as equipes da RFB, incluindo explicação detalhada da lógica de threshold dinâmico.</p>
</section>
</section>
<section id="sec-analises-aprofundadas" class="level2" data-number="B.4">
<h2 data-number="B.4" class="anchored" data-anchor-id="sec-analises-aprofundadas"><span class="header-section-number">B.4</span> Análises Aprofundadas e Validação</h2>
<p>Nesta seção, apresentamos análises detalhadas conduzidas pelos bolsistas do projeto, ilustrando aplicações práticas da metodologia desenvolvida e evidenciando padrões identificados durante a validação cruzada ArcGIS vs CNEFE.</p>
<section id="metodologia-de-recuperação-vias-curtas-short-streets" class="level3" data-number="B.4.1">
<h3 data-number="B.4.1" class="anchored" data-anchor-id="metodologia-de-recuperação-vias-curtas-short-streets"><span class="header-section-number">B.4.1</span> 1. Metodologia de Recuperação: Vias Curtas (Short Streets)</h3>
<p><em>Análise completa disponível em <a href="relatorios.qmd#sec-rel-vias-curtas">Apêndice — Análise Exploratória (Vias Curtas)</a>.</em></p>
<p><strong>Período:</strong> Janeiro - Março 2026 <strong>Objetivo:</strong> Demonstrar como registros de precisão intermediária (precisão = 3) podem ser recuperados através de análise espacial comparativa com malha viária de setores censitários únicos.</p>
<p>A descrição do fluxo operacional dessa metodologia no pipeline de tratamento encontra-se na Seção <em>Triagem de Precisão e Recuperação Espacial</em>; esta seção detalha os resultados analíticos e a validação da hipótese territorial.</p>
<section id="metodologia" class="level4" data-number="B.4.1.1">
<h4 data-number="B.4.1.1" class="anchored" data-anchor-id="metodologia"><span class="header-section-number">B.4.1.1</span> Metodologia</h4>
<p>O procedimento implementa um filtro espacial de dupla verificação:</p>
<ol type="1">
<li><strong>Seleção do Universo:</strong> Identificam-se todos os 12.077 registros classificados como precisão 3 (sem número de porta informado)</li>
<li><strong>Cálculo de Proximidade #1:</strong> Para cada registro, calcula-se a distância até a <strong>via curta mais próxima</strong> (máx. 100m)</li>
<li><strong>Cálculo de Proximidade #2:</strong> Para o mesmo registro, calcula-se a distância até a <strong>via mais próxima</strong> de toda a malha viária</li>
<li><strong>Comparação:</strong> Se ambas as distâncias forem equivalentes (tolerância ≤2-3m), conclui-se que a via curta é a principal referência</li>
<li><strong>Marcação:</strong> O registro recebe <code>flag_reap3 = True</code> (reaproveitável) ou <code>False</code> (descartável)</li>
</ol>
<p><strong>Bases Geográficas Utilizadas:</strong> - <code>eixos_osm_curtos.gpkg</code> — 1.236 vias curtas (integralmente dentro de 1 setor censitário) - <code>eixos_osm_dissolvidos.gpkg</code> — Malha viária completa - Sistema de referência: EPSG:31982 (coordenadas métricas)</p>
</section>
<section id="resultados" class="level4" data-number="B.4.1.2">
<h4 data-number="B.4.1.2" class="anchored" data-anchor-id="resultados"><span class="header-section-number">B.4.1.2</span> Resultados</h4>
<p><strong>Taxa Global de Recuperação:</strong> 10.23% dos registros de precisão 3 (1.236 de 12.077) foram reaproveitados.</p>
<p><strong>Distribuição Territorial (TOP 10 Bairros):</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Bairro</th>
<th>Precisão 3</th>
<th>Reaproveitados</th>
<th>Taxa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Rio Tavares</strong></td>
<td>196</td>
<td>61</td>
<td>31.12%</td>
</tr>
<tr class="even">
<td><strong>São João do Rio Vermelho</strong></td>
<td>361</td>
<td>86</td>
<td>23.82%</td>
</tr>
<tr class="odd">
<td><strong>Saco dos Limões</strong></td>
<td>63</td>
<td>15</td>
<td>23.81%</td>
</tr>
<tr class="even">
<td><strong>Itacorubi</strong></td>
<td>523</td>
<td>109</td>
<td>20.84%</td>
</tr>
<tr class="odd">
<td><strong>Estreito</strong></td>
<td>197</td>
<td>34</td>
<td>17.26%</td>
</tr>
<tr class="even">
<td><strong>Córrego Grande</strong></td>
<td>203</td>
<td>34</td>
<td>16.75%</td>
</tr>
<tr class="odd">
<td><strong>Agronômica</strong></td>
<td>406</td>
<td>59</td>
<td>14.53%</td>
</tr>
<tr class="even">
<td><strong>Jurerê Internacional</strong></td>
<td>901</td>
<td>121</td>
<td>13.43%</td>
</tr>
<tr class="odd">
<td><strong>Trindade</strong></td>
<td>389</td>
<td>50</td>
<td>12.85%</td>
</tr>
<tr class="even">
<td><strong>Lagoa da Conceição</strong></td>
<td>196</td>
<td>25</td>
<td>12.76%</td>
</tr>
</tbody>
</table>
<p><strong>Distribuição por Tipo de Imóvel:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tipo</th>
<th>Precisão 3</th>
<th>Reaproveitados</th>
<th>Taxa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Casa</strong></td>
<td>3.137</td>
<td>447</td>
<td>14.25%</td>
</tr>
<tr class="even">
<td><strong>Lote/Terreno</strong></td>
<td>1.230</td>
<td>151</td>
<td>12.28%</td>
</tr>
<tr class="odd">
<td><strong>Escritório</strong></td>
<td>430</td>
<td>44</td>
<td>10.23%</td>
</tr>
<tr class="even">
<td><strong>Apartamento</strong></td>
<td>5.443</td>
<td>433</td>
<td>7.96%</td>
</tr>
<tr class="odd">
<td><strong>Ponto Comercial</strong></td>
<td>283</td>
<td>26</td>
<td>9.19%</td>
</tr>
<tr class="even">
<td><strong>Casa de Condomínio</strong></td>
<td>548</td>
<td>49</td>
<td>8.94%</td>
</tr>
<tr class="odd">
<td><strong>Cobertura</strong></td>
<td>741</td>
<td>55</td>
<td>7.42%</td>
</tr>
</tbody>
</table>
<p><strong>Análise de Características (Reaproveitados vs Não Reaproveitados):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Variável</th>
<th>flag_reap3=True (Mediana)</th>
<th>flag_reap3=False (Mediana)</th>
<th>Diferença</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Valor (R$)</td>
<td>1.308.000</td>
<td>1.260.000</td>
<td>+3.8%</td>
</tr>
<tr class="even">
<td>Área (m²)</td>
<td>151</td>
<td>130</td>
<td>+16.3%</td>
</tr>
<tr class="odd">
<td>Quartos</td>
<td>3</td>
<td>3</td>
<td>—</td>
</tr>
<tr class="even">
<td>Banheiros</td>
<td>2</td>
<td>2</td>
<td>—</td>
</tr>
<tr class="odd">
<td>Vagas Garagem</td>
<td>2</td>
<td>2</td>
<td>—</td>
</tr>
</tbody>
</table>
<p><strong>Interpretação:</strong> Os registros reaproveitados apresentam áreas e valores ligeiramente maiores, sugerindo que a metodologia captura bem imóveis em localidades mais estruturadas (onde vias curtas existem).</p>
<p>A metodologia é <strong>conservadora por design</strong>: apenas 10,23% dos registros de precisão 3 passam no filtro, garantindo que apenas aqueles com evidência territorial forte sejam reaproveitados. A cobertura analítica sobe de ~73% para ~81% sem comprometer a qualidade posicional. A variação territorial observada — Rio Tavares (31%) vs.&nbsp;Ingleses do Rio Vermelho (3%) — indica que a densidade e regularidade da malha viária influenciam diretamente a taxa de recuperação.</p>
<hr>
</section>
</section>
<section id="sec-lote-terreno" class="level3" data-number="B.4.2">
<h3 data-number="B.4.2" class="anchored" data-anchor-id="sec-lote-terreno"><span class="header-section-number">B.4.2</span> Análise Exploratória: Desempenho em Lotes e Terrenos</h3>
<p><em>Análise completa disponível em <a href="relatorios.qmd#sec-rel-lote-terreno">Apêndice — Análise de Lote/Terreno V3</a>.</em></p>
<p><strong>Período:</strong> Março 2026 <strong>Objetivo:</strong> Investigar as causas raiz da menor taxa de processamento em imóveis não-edificados e propor estratégias de melhoria específicas para este segmento.</p>
<p>O achado quantitativo deste segmento é destacado em <em>Performance por Tipo de Imóvel</em> (Seção de Resultados); esta seção aprofunda a metodologia de diagnóstico, as causas raiz e as recomendações.</p>
<section id="metodologia-1" class="level4" data-number="B.4.2.1">
<h4 data-number="B.4.2.1" class="anchored" data-anchor-id="metodologia-1"><span class="header-section-number">B.4.2.1</span> Metodologia</h4>
<p>Para entender o desempenho inferior de Lotes/Terrenos, executou-se análise exploratória através de:</p>
<ol type="1">
<li><strong>Segmentação:</strong> Isolamento dos 6.120 registros classificados como tipo_imovel = “Lote/Terreno”</li>
<li><strong>Métricas Comparativas:</strong> Cálculo de taxa de processamento, conformidade &lt;150m, distância média/mediana vs média geral</li>
<li><strong>Análise Geográfica:</strong> Identificação de bairros com pior performance neste segmento</li>
<li><strong>Análise de Matching:</strong> Distribuição por tipo de match CNEFE (exact, fuzzy_number, fuzzy_street, etc.)</li>
</ol>
</section>
<section id="resultados-1" class="level4" data-number="B.4.2.2">
<h4 data-number="B.4.2.2" class="anchored" data-anchor-id="resultados-1"><span class="header-section-number">B.4.2.2</span> Resultados</h4>
<p><strong>Taxa de Processamento Comparativa:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Métrica</th>
<th>Lote/Terreno</th>
<th>Geral</th>
<th>Diferença</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Taxa de Processamento</td>
<td>55.0% (3.369 de 6.120)</td>
<td>89.6% (54.007 de 60.230)</td>
<td><strong>-34.6%</strong></td>
</tr>
<tr class="even">
<td>Conformidade &lt;150m</td>
<td>33.66% (1.134 de 3.369)</td>
<td>47.83% (25.325 de 52.950)</td>
<td><strong>-14.17%</strong></td>
</tr>
<tr class="odd">
<td>Distância Média</td>
<td>569.92 m</td>
<td>215.26 m</td>
<td><strong>+354.66 m</strong></td>
</tr>
<tr class="even">
<td>Distância Mediana</td>
<td>52.71 m</td>
<td>24.35 m</td>
<td><strong>+28.36 m</strong></td>
</tr>
</tbody>
</table>
<p><strong>Bairros com Pior Performance (Lote/Terreno):</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Bairro</th>
<th>Total</th>
<th>OK</th>
<th>% OK</th>
<th>Dist. Média</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ratones</td>
<td>177</td>
<td>18</td>
<td>10.2%</td>
<td>505.2 m</td>
</tr>
<tr class="even">
<td>Ingleses do Rio Vermelho</td>
<td>282</td>
<td>60</td>
<td>21.3%</td>
<td>2.028.1 m</td>
</tr>
<tr class="odd">
<td>São João do Rio Vermelho</td>
<td>146</td>
<td>33</td>
<td>22.6%</td>
<td>717.6 m</td>
</tr>
<tr class="even">
<td>Rio Tavares</td>
<td>132</td>
<td>38</td>
<td>28.8%</td>
<td>570.6 m</td>
</tr>
<tr class="odd">
<td>Itacorubi</td>
<td>128</td>
<td>33</td>
<td>25.8%</td>
<td>151.1 m</td>
</tr>
<tr class="even">
<td>Centro</td>
<td>139</td>
<td>38</td>
<td>27.3%</td>
<td>453.9 m</td>
</tr>
</tbody>
</table>
<p><strong>Distribuição por Tipo de Match CNEFE:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tipo de Match</th>
<th>Total</th>
<th>Dist. Média</th>
<th>Dist. Mediana</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>fuzzy_number</td>
<td>2.206</td>
<td>524.1 m</td>
<td>86.5 m</td>
</tr>
<tr class="even">
<td>exact_cep_street_number</td>
<td>964</td>
<td>640.2 m</td>
<td>17.4 m</td>
</tr>
<tr class="odd">
<td>fuzzy_street</td>
<td>166</td>
<td>804.6 m</td>
<td>256.2 m</td>
</tr>
<tr class="even">
<td>fuzzy_bairro</td>
<td>33</td>
<td>396.6 m</td>
<td>221.3 m</td>
</tr>
<tr class="odd">
<td>no_match</td>
<td>108</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
<p><strong>Causas raiz identificadas:</strong></p>
<ol type="1">
<li><strong>Ausência de numeração:</strong> 45% dos lotes não têm match CNEFE porque não possuem número de porta definido</li>
<li><strong>Prioridade CNEFE:</strong> a base oficial prioriza edificações; lotes vagos têm cobertura reduzida</li>
<li><strong>Áreas de expansão:</strong> lotes em periferias concentram precisão IBGE baixa (<code>nv_geo_coord</code> = 5–6)</li>
<li><strong>Score L2 degradado:</strong> com diferenças numéricas acima de 100 (ex: lote 100 vs.&nbsp;CNEFE 500), o componente numérico do score cai drasticamente — score = 0,65×0,95 + 0,35×(1÷401) = <strong>0,618</strong> (abaixo do threshold 0,80)</li>
</ol>
<hr>
</section>
</section>
<section id="validação-de-acurácia-benchmarking-com-google-maps" class="level3" data-number="B.4.3">
<h3 data-number="B.4.3" class="anchored" data-anchor-id="validação-de-acurácia-benchmarking-com-google-maps"><span class="header-section-number">B.4.3</span> Validação de Acurácia (Benchmarking com Google Maps)</h3>
<p><em>Análise completa disponível em <a href="relatorios.qmd#sec-rel-estatistica">Apêndice — Análise Estatística V3</a> e <a href="relatorios.qmd#sec-rel-cnefe">Avaliação CNEFE V3</a>.</em></p>
<p><strong>Autor:</strong> Ville Rodrigues <strong>Período:</strong> Abril 2026 <strong>Objetivo:</strong> Avaliar a qualidade das coordenadas do CNEFE e do ArcGIS tomando o Google Maps como referência de maior acurácia (Ground Truth).</p>
<section id="metodologia-2" class="level4" data-number="B.4.3.1">
<h4 data-number="B.4.3.1" class="anchored" data-anchor-id="metodologia-2"><span class="header-section-number">B.4.3.1</span> Metodologia</h4>
<p>A análise comparou três pares de coordenadas em quatro níveis de geocodificação do IBGE (<code>NV_GEO_COORD</code>): - <strong>ArcGIS × Google:</strong> Avalia o erro do provedor de mercado. - <strong>CNEFE × Google:</strong> Avalia o erro da base oficial. - <strong>CNEFE × ArcGIS:</strong> Avalia a convergência entre as fontes alternativas.</p>
<p>A amostra abrangeu aproximadamente 3.200 anúncios geocodificados manualmente no Google Maps para garantir a integridade da comparação.</p>
</section>
<section id="resultados-sintéticos" class="level4" data-number="B.4.3.2">
<h4 data-number="B.4.3.2" class="anchored" data-anchor-id="resultados-sintéticos"><span class="header-section-number">B.4.3.2</span> Resultados Sintéticos</h4>
<p>A tabela abaixo resume as medianas de distância (em metros) para os quatro níveis de precisão do CNEFE:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Nível (NV_GEO_COORD)</th>
<th style="text-align: left;">Descrição IBGE</th>
<th style="text-align: center;">Mediana ArcGIS × Google (m)</th>
<th style="text-align: center;">Mediana CNEFE × Google (m)</th>
<th style="text-align: center;">Mediana CNEFE × ArcGIS (m)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>1</strong></td>
<td style="text-align: left;">Urbana: Edificação</td>
<td style="text-align: center;">17,10</td>
<td style="text-align: center;">27,63</td>
<td style="text-align: center;">23,85</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>2</strong></td>
<td style="text-align: left;">Urbana: Face de quadra</td>
<td style="text-align: center;">21,99</td>
<td style="text-align: center;">26,04</td>
<td style="text-align: center;">12,59</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>3</strong></td>
<td style="text-align: left;">Urbana: Centro de quadra</td>
<td style="text-align: center;">20,15</td>
<td style="text-align: center;">37,80</td>
<td style="text-align: center;">31,48</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>4</strong></td>
<td style="text-align: left;">Urbana: Setor/Outros</td>
<td style="text-align: center;">25,56</td>
<td style="text-align: center;">45,20</td>
<td style="text-align: center;">64,88</td>
</tr>
</tbody>
</table>
</section>
<section id="principais-conclusões-do-estudo" class="level4" data-number="B.4.3.3">
<h4 data-number="B.4.3.3" class="anchored" data-anchor-id="principais-conclusões-do-estudo"><span class="header-section-number">B.4.3.3</span> Principais Conclusões do Estudo</h4>
<ol type="1">
<li><strong>Performance Relativa:</strong> No caso típico (mediana), o <strong>ArcGIS foi mais próximo do Google em todos os níveis</strong>, indicando que as coordenadas de mercado são altamente competitivas para uso imediato.</li>
<li><strong>O Trunfo do Nível 2:</strong> O <strong>Nível 2 (Face de Quadra)</strong> apresentou o quadro mais equilibrado, com o CNEFE mostrando leve vantagem acumulada nas faixas de até 50m e 100m, demonstrando ser a faixa de maior confiabilidade da base oficial.</li>
<li><strong>Fragilidade no Nível 4:</strong> O Nível 4 revelou a maior degradação do CNEFE, com mediana de erro de <strong>45,20m</strong> contra o Google, reforçando a necessidade de thresholds mais largos (500m+) para esta categoria no modelo V3.</li>
<li><strong>Confiabilidade do Match Exato:</strong> O tipo de correspondência <code>exact_cep_street_number</code> (L1) provou ser o mais robusto no CNEFE, com 88,3% dos casos dentro de 50m do ponto real do Google no Nível
<ol type="1">
<li></li>
</ol></li>
<li><strong>Heterogeneidade Espacial:</strong> O estudo confirmou que a precisão não é uniforme; bairros como o <strong>Centro</strong> apresentam alta aderência em ambas as fontes, enquanto áreas como <strong>Ponta das Canas</strong> sofrem com deslocamentos significativos no CNEFE.</li>
</ol>
<p>O estudo conclui que o ArcGIS é, em média, a fonte que mais se aproxima do ponto de referência ideal. Contudo, o CNEFE — especialmente em <code>nv_geo_coord</code> 1 e 2 — é uma fonte validadora robusta. O uso do CNEFE deve ser sempre <strong>qualificado pelo nível de precisão e tipo de correspondência</strong>, conforme implementado na lógica do Geocoder V3.</p>
<hr>
</section>
</section>
<section id="recomendações-e-próximos-passos" class="level3" data-number="B.4.4">
<h3 data-number="B.4.4" class="anchored" data-anchor-id="recomendações-e-próximos-passos"><span class="header-section-number">B.4.4</span> Recomendações e Próximos Passos</h3>
<p>Para consolidar os aprendizados da POC Florianópolis e escalar para Lote 1 e Lote 2, recomenda-se:</p>
<ol type="1">
<li><strong>Benchmark V2 vs V3:</strong> Comparação quantitativa de todas as métricas entre as duas versões do Geocoder</li>
<li><strong>Análise de Outliers:</strong> Investigação manual dos 9.625 registros com distância &gt; 500m (erros potenciais)</li>
<li><strong>Ajuste de Thresholds Lote/Terreno:</strong> Aumentar tolerância numérica de ±50 para ±100 dígitos especificamente neste tipo</li>
<li><strong>Integração de Fontes Secundárias:</strong> OpenStreetMap e Google Maps para preenchimento dos 12% sem match CNEFE</li>
<li><strong>Modelagem Preditiva:</strong> Treinar ML para predizer <code>is_problematic</code> antes do processamento (priorizar revisão manual)</li>
</ol>
<hr>
</section>
</section>
<section id="desafios" class="level2" data-number="B.5">
<h2 data-number="B.5" class="anchored" data-anchor-id="desafios"><span class="header-section-number">B.5</span> Desafios</h2>
<section id="qualidade-de-dados" class="level3" data-number="B.5.1">
<h3 data-number="B.5.1" class="anchored" data-anchor-id="qualidade-de-dados"><span class="header-section-number">B.5.1</span> Qualidade de dados</h3>
<p>Os dados fornecidos pelas APIs imobiliárias apresentam alto nível de ruído: CEPs incorretos, números de porta ausentes ou logradouros preenchidos no campo de bairro.</p>
</section>
<section id="validação-posicional-e-integridade-da-oferta-são-processos-independentes" class="level3" data-number="B.5.2">
<h3 data-number="B.5.2" class="anchored" data-anchor-id="validação-posicional-e-integridade-da-oferta-são-processos-independentes"><span class="header-section-number">B.5.2</span> Validação Posicional e Integridade da Oferta são Processos Independentes</h3>
<p>A Detecção de Outliers e a Validação Posicional (Geocoder V3) rodam em paralelo sobre a mesma base e produzem flags independentes. Uma oferta pode ter a posição confirmada pelo CNEFE e ainda assim ser uma duplicata, ter número de quartos, área ou valor/m² fora do esperado, ou campos obrigatórios ausentes — e vice-versa. Os dois processos não se invalidam: eles respondem a perguntas diferentes.</p>
<p>Isso tem uma implicação direta sobre os números de cobertura. O Geocoder V3 validou posicionalmente <strong>25.325 ofertas</strong> (<code>is_problematic = FALSE</code>). Mas essas 25.325 não são homogêneas:</p>
<ul>
<li><strong>14.921</strong> → posição validada <strong>e</strong> oferta íntegra</li>
<li><strong>6.982</strong> → posição validada, mas são <strong>duplicatas</strong></li>
<li><strong>3.419</strong> → posição validada, mas com <strong>atributos da oferta suspeitos</strong> (área, vagas, valor/m²)</li>
<li><strong>3</strong> → posição validada, mas com <strong>campos obrigatórios ausentes</strong></li>
</ul>
<p>O número que efetivamente combina os dois critérios — posição validada e oferta íntegra — é <strong>14.921 imóveis</strong>.</p>
<section id="problema-crítico-lotesterrenos" class="level4" data-number="B.5.2.1">
<h4 data-number="B.5.2.1" class="anchored" data-anchor-id="problema-crítico-lotesterrenos"><span class="header-section-number">B.5.2.1</span> Problema Crítico: Lotes/Terrenos</h4>
<p>Uma dificuldade notável ocorre com Lotes e Terrenos, onde a taxa de processamento foi apenas <strong>55.0%</strong> (3.369 de 6.120 imóveis), 34,6 pontos percentuais abaixo da média geral. As principais causas são a ausência de numeração de porta em lotes vagos, a menor cobertura do CNEFE para imóveis não-edificados e a degradação do score no L2 (fuzzy_number) quando a diferença numérica entre lote e edificação vizinha supera ~100 unidades.</p>
<p>A análise completa — com tabelas comparativas por bairro, distribuição por tipo de match e recomendações de ajuste de threshold — está documentada na <a href="#sec-lote-terreno">Seção 3.2</a> e no <a href="relatorios.qmd#sec-rel-lote-terreno">Apêndice — Análise de Lote/Terreno</a>.</p>
</section>
</section>
<section id="padronização" class="level3" data-number="B.5.3">
<h3 data-number="B.5.3" class="anchored" data-anchor-id="padronização"><span class="header-section-number">B.5.3</span> Padronização</h3>
<p>Enfrentamos o desafio de comparar strings com grafias distintas (ex: “Av. Brigadeiro”, “Avenida Brig.”, “Brig.”). A adoção do <em>trigram matching</em> com PostgreSQL e da extensão <code>unaccent</code> resolveu a maioria das ocorrências, porém exigiu um ajuste fino dos thresholds de score.</p>
</section>
<section id="integração" class="level3" data-number="B.5.4">
<h3 data-number="B.5.4" class="anchored" data-anchor-id="integração"><span class="header-section-number">B.5.4</span> Integração</h3>
<p>Conectar bases massivas sem travar a memória ou demorar dias de processamento exigiu reestruturar o pipeline inicial para uso pesado de índices (<code>GIN</code> em PostgreSQL). Além disso, definir qual coordenada “vence” (ArcGIS ou CNEFE) demandou regras complexas que levassem em conta as variáveis <code>nv_geo_coord</code> (precisão do IBGE) versus a <code>precisao</code> (do ArcGIS).</p>
</section>
</section>
<section id="escalabilidade" class="level2" data-number="B.6">
<h2 data-number="B.6" class="anchored" data-anchor-id="escalabilidade"><span class="header-section-number">B.6</span> Escalabilidade</h2>
<section id="replicabilidade-do-modelo" class="level3" data-number="B.6.1">
<h3 data-number="B.6.1" class="anchored" data-anchor-id="replicabilidade-do-modelo"><span class="header-section-number">B.6.1</span> Replicabilidade do modelo</h3>
<p>A arquitetura baseada no Geocoder V3 demonstrou maturidade para escalabilidade. A execução via batch alcançou processamentos acima de 50.000 registros em pouco mais de 2 minutos. O modelo é idempotente, permitindo reinícios sem duplicação, garantindo total replicação para as demais praças nacionais no decorrer dos Lotes 1 e 2.</p>
</section>
<section id="dependências-externas" class="level3" data-number="B.6.2">
<h3 data-number="B.6.2" class="anchored" data-anchor-id="dependências-externas"><span class="header-section-number">B.6.2</span> Dependências externas</h3>
<p>Embora robusto, o modelo depende intrinsecamente do avanço do mapeamento do IBGE (CNEFE). Para perfis críticos onde a base governamental tem menor cobertura — como Lotes Vagos ou condomínios em desenvolvimento inicial — a arquitetura já sugere a possibilidade de integração futura com oráculos secundários (Google Maps Geocoding API ou OpenStreetMap Nominatim).</p>
</section>
</section>
<section id="conclusão" class="level2" data-number="B.7">
<h2 data-number="B.7" class="anchored" data-anchor-id="conclusão"><span class="header-section-number">B.7</span> Conclusão</h2>
<p>A Prova de Conceito realizada em Florianópolis atestou a viabilidade técnica e a escalabilidade da arquitetura proposta para o <strong>Observatório do Mercado Imobiliário</strong>. Ao adotar o CNEFE como <em>ground truth</em> e implementar o motor de validação cruzada <strong>Geocoder V3</strong>, o projeto superou a dependência exclusiva de coordenadas comerciais autodeclaradas, estabelecendo um novo padrão de rigor posicional e econômico sobre a base de dados imobiliários.</p>
<p>A metodologia adotada produziu dois eixos independentes de qualidade posicional (<code>is_problematic</code>) e econômico-cadastral (<code>is_outlier</code>), que podem ser combinados conforme o objetivo de cada análise. Essa independência é uma característica deliberada: permite que o analista da RFB aplique filtros progressivos sem descartar dados que podem ser úteis em contextos distintos.</p>
<section id="resultado-final-base-duplamente-validada" class="level3" data-number="B.7.1">
<h3 data-number="B.7.1" class="anchored" data-anchor-id="resultado-final-base-duplamente-validada"><span class="header-section-number">B.7.1</span> Resultado Final: Base Duplamente Validada</h3>
<p>Aplicando simultaneamente os dois filtros de qualidade — <code>is_outlier = 0</code> (dado econômico limpo, sem duplicatas e campos válidos) <strong>e</strong> <code>is_problematic = FALSE</code> (posição confirmada pelo CNEFE) —, o resultado da PoC Florianópolis é:</p>
<div style="border-left: 4px solid #555; background-color: #f5f5f5; padding: 1.2em 1.5em; margin: 1.5em 0;">
<p><strong>Dataset Pronto para Análise Fiscal Direta</strong></p>
<p><strong>14.921 imóveis</strong> com posição validada e oferta íntegra — <strong>17,8% da base bruta</strong> (83.869 registros).</p>
<table class="caption-top table">
<caption>Lote/Terreno representa apenas <strong>5,0%</strong> das ofertas duplamente validadas — reflexo direto da menor taxa de processamento CNEFE (55% vs. 89,6% geral), discutida na <a href="#sec-lote-terreno">Seção 3.2</a>. A expansão dessa cobertura é uma das prioridades dos próximos passos.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Métrica</th>
<th style="text-align: right;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Imóveis validados (duplo filtro)</td>
<td style="text-align: right;"><strong>14.921</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Distância mediana ao CNEFE</td>
<td style="text-align: right;"><strong>8,86m</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Distância média ao CNEFE</td>
<td style="text-align: right;"><strong>17,73m</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Composição principal</td>
<td style="text-align: right;">Apartamento (7.327) · Casa (4.266) · Cobertura (1.082) · Lote/Terreno (753)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tipo de negócio</td>
<td style="text-align: right;">Venda (14.525) · Aluguel (294) · Venda/Aluguel (102)</td>
</tr>
</tbody>
</table>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">-- Filtro recomendado para análise fiscal direta</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="kw">SELECT</span> <span class="op">*</span> <span class="kw">FROM</span> _projeto_rf.monit_2025_11_poc_floripa_v3</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="kw">WHERE</span> is_outlier <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="kw">AND</span> is_problematic <span class="op">=</span> <span class="kw">FALSE</span>;</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>A mediana de <strong>8,86m</strong> de divergência posicional entre a coordenada de mercado (ArcGIS) e a oficial (CNEFE) neste subconjunto é significativamente melhor do que a mediana global de 24,35m — evidenciando que os registros mais limpos economicamente também tendem a ter endereçamento mais preciso.</p>
<p>Embora desafios persistam — especialmente na geocodificação de Lotes Vagos e áreas de expansão urbana —, o arcabouço tecnológico está maduro. O Observatório encontra-se estruturalmente preparado para avançar em sua expansão territorial (Lotes 1 e 2) e para dar início às fases de modelagem preditiva e inteligência fiscal que constituem o seu objetivo final.dei</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./91-fluxo.html" class="pagination-link" aria-label="Fluxo Metodológico">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Fluxo Metodológico</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./93-metodo-etapa02.html" class="pagination-link" aria-label="Materiais, Métodos e Resultados da Etapa 2 - Bases Cartográficas Territoriais">
        <span class="nav-page-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Materiais, Métodos e Resultados da Etapa 2 - Bases Cartográficas Territoriais</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 UFSC</p>
</div>   
    <div class="nav-footer-center">
<p><img src="img/Logo com RFB e UFSC.png" class="img-fluid" width="250"></p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/LabFSG-UFSC/Rel_1T2026/edit/main/92-metodo-etapa01.qmd" class="toc-action"><i class="bi bi-github"></i>Editar essa página</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>